version: '3'

services:
  db:
    container_name: wish-db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wish-db
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
  search-service:
    container_name: search
    image: ghcr.io/agustinvon/search-service-aseca:main
    ports:
      - 4000:4000
    expose:
      - '4000'
    command: npm run dev

volumes:
  pgdata: {}